---
metadata:
 name: "Check that all resources are tagged with the key - environment"
 id: "CKV2_AZURE_1"
 category: "GENERAL_SECURITY"
scope:
 provider: azure
definition:
 and:
     - cond_type: "attribute"
       resource_types: "all"
       attribute: "tags.environment"
       operator: "exists"
     - cond_type: "attribute"
       resource_types: "all"
       attribute: "tags.environment"
       operator: "is_not_null"
